markdown: rdiscount
permalink: /:title/
url: http://github.kalikar.com
highlighter: pygments
name: zhan
description: zhan | Stop talking, start doing.
author: kalikar
email: kalikarzhan@gmail.com
disqus: kalikarzhan
hub: zhan
safe: true
paginate: 100
about: ""
