markdown: rdiscount
permalink: /:title/
url: http://github.kalikar.com
highlighter: pygments
name: zhan
description: zhan | Stop talking, start doing.
author: kalikar
email: kalikar@aliyun.com
disqus: kalikar
hub: kalikar
safe: true
paginate: 100
about: ""
